version: '3'

services: 

  app:
      build: 
        context: ./node
        dockerfile : Dockerfile
      container_name: app
      networks: 
        - node-network
      volumes: 
        - ./node:/usr/src/app
      tty: true
  

  nginx:
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      container_name: nginx
      networks: 
        - node-network
      ports:
        - "8080:80"
      depends_on: 
        - app
   

networks: 
  node-network:
    driver: bridge   